# test:
#   path: /test/{age<\d+>?0}
#   controller: App\Controller\TestController::test
#   methods: [GET, POST]
#   # host: localhost
#   schemes: [https, http]
  # host: {subdomain}.monsite.com
  # api.monsite.com && www.monsite.com && monsite.com
  # api.monsite.com / www.monsite.com
  # defaults: 
  #   age: 0
  # requirements:
  #   age: \d+